version: "3.2"

services:
    
  web:
    image: gotson/komga:latest
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/data:/data
    ports: "25600:25600"
    user: "1000:1000"
    environment:
      - TZ=America/Toronto
    restart: unless-stopped
    container_name: reus-komga_web_1
