services:

  app_proxy:
    environment:
       APP_HOST: reus-komga_web_1
       APP_PORT: 42069
    container_name: nreus-komga_app_proxy_1
    
  web:
    image: gotson/komga:latest
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/data:/data
    ports:
      - "42069:25600"
    user: "1000:1000"
    environment:
      - TZ=America/Toronto
    restart: unless-stopped
    container_name: reus-komga_web_1
