version: "3.7"

services:
      
  komga:
    image: gotson/komga:latest
    ports:
      - "42069:25600"
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/data:/data
    user: "1000:1000"
    environment:
      - TZ=America/Toronto
    restart: unless-stopped
