version: "3.2"

services:
  app_proxy:
    environment:
      APP_HOST: nreus-komga-server_web_1
      APP_PORT: 42069
      
  web:
    image: gotson/komga:latest
    ports:
      - "42069:25600"
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/data:/data
    user: "1000:1000"
    environment:
      - TZ=America/Toronto
    restart: unless-stopped
